### PR TITLE
fix: Move em.register calls out of the cstr.

### LINKED ISSUE #1564: IndexManager fails on ReactiveReferences without transformer
I.e. if `Location.ts` has a `Location.group = hasReactiveReference` that is not initted until after the constructor (b/c we don't have the transformer installed in tsx) then this can happen:

```
graphql-1  |   TypeError: Cannot read properties of undefined (reading 'isSet')
graphql-1  |       at getFieldValue (/home/node/app/node_modules/joist-orm/src/IndexManager.ts:139:27)
graphql-1  |       at IndexManager.addEntitiesToIndex (/home/node/app/node_modules/joist-orm/src/IndexManager.ts:113:23)
graphql-1  |       at IndexManager.maybeIndexEntity (/home/node/app/node_modules/joist-orm/src/IndexManager.ts:54:12)
graphql-1  |       at EntityManager.register (/home/node/app/node_modules/joist-orm/src/EntityManager.ts:1339:24)
graphql-1  |       at new BaseEntity (/home/node/app/node_modules/joist-orm/src/BaseEntity.ts:49:10)
graphql-1  |       at new LocationCodegen (/home/node/app/src/entities/codegen/LocationCodegen.ts:459:5)
graphql-1  |       at new Location (/home/node/app/src/entities/Location.ts:31:8)
graphql-1  |       at EntityManager.create (/home/node/app/node_modules/joist-orm/src/EntityManager.ts:684:12)
graphql-1  |       at DataLoader.em.getLoader.cacheKeyFn.cacheKeyFn (/home/node/app/node_modules/joist-orm/src/dataloaders/findOrCreateDataLoader.ts:111:21)
graphql-1  |       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
graphql-1  |       at findOrCreate (/home/node/app/node_modules/joist-orm/src/EntityManager.ts:673:32)
graphql-1  |       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
graphql-1  |       at async EntityManager.findOrCreate (/home/node/app/node_modules/joist-orm/src/EntityManager.ts:670:20)
graphql-1  |       at async Location.findOrCreateDpGeneralizedLocationFromPpLocation (/home/node/app/src/entities/Location.ts:267:10)
graphql-1  |       at async copyPlanPackageTlis (/home/node/app/src/jobs/copyTemplateItems/copyPlanPackageToDesignPackage.ts:119:7)
graphql-1  |       at async copyPlanPackageToDesignPackage (/home/node/app/src/jobs/copyTemplateItems/copyPlanPackageToDesignPackage.ts:31:3)
graphql-1  |       at async <anonymous> (/home/node/app/node_modules/joist-orm/src/EntityManager.ts:1308:22)
graphql-1  |       at async <anonymous> (/home/node/app/node_modules/joist-orm/src/drivers/PostgresDriver.ts:87:24)
```

### PR DESCRIPTION
**Pull request by stephenh**
Fixes #1564

Deprecates `new Entity(em, opts)` and forces `em.create(Entity, opts)` because the `em.create` is the only way we can do safe opts handling after the entity is fully instantiated, with all subtype-driven fields/relations.

### CODE REVIEW

File: packages/orm/src/EntityManager.ts [hunk 1]
```diff
@@ -89,7 +89,7 @@ import { assertNever, fail, failIfAnyRejected, getOrSet, groupBy, MaybePromise,
  * implement this and instead only have the `AbsEntityConstructor` type.
  */
 export interface EntityConstructor<T> {
-  new (em: EntityManager<any, any, any>, opts: any): T;
+  new (em: EntityManager<any, any, any>, isNew: boolean): T;
```
Comment (zgavin) [inline packages/orm/src/EntityManager.ts]: thought: should this be `protected new`? can you even do that in an interface?

File: packages/tests/bun-sql-pg/src/entities/codegen/AuthorCodegen.ts [hunk 2]
```diff
@@ -123,9 +123,8 @@ export abstract class AuthorCodegen extends BaseEntity<EntityManager, string> im
 
   declare readonly __type: { 0: "Author" };
 
-  constructor(em: EntityManager, opts: AuthorOpts) {
-    super(em, opts);
-    setOpts(this as any as Author, opts, { calledFromConstructor: true });
+  constructor(em: EntityManager, isNew: boolean) {
```
Comment (zgavin) [inline packages/tests/bun-sql-pg/src/entities/codegen/AuthorCodegen.ts]: thought: should we also make these codegen constructors `protected`?

File: packages/orm/src/EntityManager.ts [hunk 3]
```diff
@@ -2227,6 +2220,23 @@ export class EntityManager<C = unknown, Entity extends EntityW = EntityW, TX ext
 
     return result as any;
   }
+
+  /** Creates a new `type` and marks it as loaded, i.e. we know its collections are all safe to access in memory. */
+  #doCreate<T extends EntityW>(type: EntityConstructor<T>, opts: any, partial: boolean): T {
+    // The constructor will run setOpts which handles defaulting collections to the right state.
```
Comment (zgavin) [inline packages/orm/src/EntityManager.ts]: question: this comment seems incorrect now since `setOpts` is being called below this?

**Review by zgavin — APPROVED** [review]

File: packages/orm/src/EntityManager.ts (hunk 1 above)
Comment (stephenh) [reply packages/orm/src/EntityManager.ts]: I tried `protected` yes in the `...Codegen` output, and right the interface / type-checker immediately caught "wait that cannot be protected if its part of this interface", so had to back it out.

File: packages/orm/src/EntityManager.ts (hunk 3 above)
Comment (stephenh) [reply packages/orm/src/EntityManager.ts]: Ah yep, thought I removed that, but must have missed it
